Improve data dictionary script usage
ncopenpass/CampaignFinance pull request #157
Opened 2020-09-15 22:20 UTC by mcelestini

- add a scripts readme
- add a command to make file to build the data dictionary
- improve the script

2020-09-15 22:58 UTC, SchaeStewart commented on docs/scripts.md
> +To build `dataDictionary.json`, paste a tab delimited .txt file into the root of the repo and run `make build-dictionary`
Can you add an example header with the fields you expect. Also document the default filename, and how to pass a custom file name if possible

2020-09-16 14:36 UTC, mcelestini commented on docs/scripts.md
> +To build `dataDictionary.json`, paste a tab delimited .txt file into the root of the repo and run `make build-dictionary`
I'm actually not sure how to get command line params to work with a makefile. I tried following this SO post
https://stackoverflow.com/questions/6273608/how-to-pass-argument-to-makefile-from-command-line
with the following changes
```
build-dictionary:
	cd scripts && node createDataDictionary $(filter-out, $@, $(MAKECMDGOALS))
```
but no luck when I try something like
`make build-dictionary myFile.txt`

2020-09-26 18:57 UTC, SchaeStewart requested changes

2020-09-26 18:57 UTC, SchaeStewart commented on docs/scripts.md
> +To build `dataDictionary.json`, paste a tab delimited .txt file into the root of the repo and run `make build-dictionary`
Yeah, make doesn't really work well with arguments. For the makefile you can use a sane default. For the documentation, just show how to run the script manually/with a custom file path. Also we need to document what headers are expected in the file

2020-10-05 23:13 UTC, mcelestini commented
@SchaeStewart I think I've addressed everything, let me know if this is good to go and I can merge it 👍

2020-10-07 00:21 UTC, SchaeStewart approved these changes
Merge when ready

2020-10-13 22:13 UTC, merged