Candidate and Non-candidate PAC pages
ncopenpass/CampaignFinance pull request #251
Opened 2021-04-27 00:13 UTC by alexisbarnes

- Candidate PAC links to candidate page (per Jeremy's request)
- Non-candidate PACs have their own page:
<img width="1621" alt="Screen Shot 2021-04-26 at 8 01 45 PM" src="https://user-images.githubusercontent.com/16669854/116165715-74e98e00-a6ca-11eb-9965-6d7d06eaf5b4.png">

**KNOWN BUGS**

- I made the NULLs return on the search results page 😅:
<img width="1245" alt="Screen Shot 2021-04-26 at 8 02 07 PM" src="https://user-images.githubusercontent.com/16669854/116165787-98143d80-a6ca-11eb-9167-fd4b59cba5a5.png">

- Links on the Contributors page are broken if the contributor has given to a PAC. The PAC shows as "NULL NULL NULL":
<img width="1138" alt="Screen Shot 2021-04-26 at 8 06 42 PM" src="https://user-images.githubusercontent.com/16669854/116165954-ee817c00-a6ca-11eb-93a5-91a719b3cc84.png">

- Download Results not working (error: "unable to process request")
<img width="1633" alt="Screen Shot 2021-04-26 at 8 12 18 PM" src="https://user-images.githubusercontent.com/16669854/116166306-b595d700-a6cb-11eb-8df5-4fa4140b42d3.png">

- The test build fails (getting this via email from Github)

Made lots to changes so open to feedback or requests. Thanks!! 😊

2021-04-27 01:39 UTC, SchaeStewart commented on server/lib/queries.js
> +      where contributor_id IS NULl
typo: change `NUL1` to `NULL`

2021-04-27 01:49 UTC, SchaeStewart requested changes
@alexisbarnes it looks pretty good overall. Congrats on making your first backend PR (I think)!

I do think we should add additional tests and add to the `api_doc.md` before the changes are merged though.  
For the tests you should be able to copy what's already there for the candidates.

Regarding the NULLs coming back, when was the last time you ran `make clean-db`? If you did it before my fix for that was merged it could explain why they returned.

Regarding the failing CSV download, you should be able to check the logs and see the error. If you need additional help, just let me know. I'm happy to pull down the changes and take a look :smile: 

Great job overall, I hope the API wasn't too confusing.

2021-04-27 20:58 UTC, alexisbarnes commented
> @alexisbarnes it looks pretty good overall. Congrats on making your first backend PR (I think)!
> 
> I do think we should add additional tests and add to the `api_doc.md` before the changes are merged though.
> For the tests you should be able to copy what's already there for the candidates.
> 
> Regarding the NULLs coming back, when was the last time you ran `make clean-db`? If you did it before my fix for that was merged it could explain why they returned.
> 
> Regarding the failing CSV download, you should be able to check the logs and see the error. If you need additional help, just let me know. I'm happy to pull down the changes and take a look 😄
> 
> Great job overall, I hope the API wasn't too confusing.

It is my first backend PR! 😭

I haven't ran `make clean-db` in a while so I will try that. The API is well organized and straightforward to follow! 🎉  Thanks for the feedback!

2021-04-28 19:25 UTC, mcelestini commented
@alexisbarnes this is awesome 👏  I just test drove it and it works like a charm. I think we can fix the individual contributor page not showing committee name and going to the candidate page instead of the committee page with the following diff. This is kind of hard to read in a comment so let me know if you've got any questions about this, but if you make this change to `useTableColumns` at line `132`, this should do the trick with showing the committee name and going to the right page

```-        accessor: ({ candidate_full_name, committee_sboe_id }) => (
-          <Link
-            to={(location) => ({
-              pathname: CANDIDATE_URL + committee_sboe_id,
-              fromPathname: location.pathname,
-            })}
-          >
-            {' '}
-            {candidate_full_name}
-          </Link>
-        ),
+        accessor: ({
+          candidate_full_name,
+          committee_sboe_id,
+          committee_name,
+        }) =>
+          Boolean(candidate_full_name) ? (
+            <Link
+              to={(location) => ({
+                pathname: CANDIDATE_URL + committee_sboe_id,
+                fromPathname: location.pathname,
+              })}
+            >
+              {' '}
+              {candidate_full_name}
+            </Link>
+          ) : (
+            <Link
+              to={(location) => ({
+                pathname: COMMITTEE_URL + committee_sboe_id,
+                fromPathname: location.pathname,
+              })}
+            >
+              {' '}
+              {committee_name}
+            </Link>
+          ),```

2021-04-28 19:26 UTC, mcelestini commented on src/components/Committee.js
> +              Total Number of Aggregated Contributions:
I don't remember if we have this data yet, do we want to keep it in here?

2021-04-28 20:48 UTC, mcelestini approved these changes

2021-04-28 23:07 UTC, alexisbarnes commented
@SchaeStewart I think I fixed all the issues. How does it look?

2021-04-28 23:19 UTC, SchaeStewart approved these changes
Looks good! Merge whenever you're ready

2021-04-29 12:34 UTC, merged